export const CREATE_USER = "CREATE_USER";
export const ERROR_CREATE_USER = "ERROR_CREATE_USER";
export const CLEAN_MSG_ALERT = "CLEAN_MSG_ALERT";

export const LOG_IN = "LOG_IN";
export const LOG_IN_ERROR = "LOG_IN_ERROR";
export const GET_DATA_USER = "GET_DATA_USER";
export const LOG_OUT = "LOG_OUT";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDDEN_ALERT = "HIDDEN_ALERT";


export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const ADD_TRANSACTION_ERROR = "ADD_TRANSACTION_ERROR";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const UPDATE_AMMOUNT = "UPDATE_AMMOUNT";
export const CATCH_TRANSACTION_TO_UPDATE = "CATCH_TRANSACTION_TO_UPDATE";
export const CANCEL_CATCH_TRANSACTION_TO_UPDATE =
  "CANCEL_CATCH_TRANSACTION_TO_UPDATE";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
