export const CREATE_USER = 'CREATE_USER';
export const USER_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS';
export const USER_CREATED = 'USER_CREATED';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_AMMOUNT = 'UPDATE_AMMOUNT';
export const CATCH_TRANSACTION_TO_UPDATE = 'CATCH_TRANSACTION_TO_UPDATE';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
